### PR TITLE
Addition of citation feature in population models

### LINKED ISSUE #46: Citation feature for population models
We could include a metadata tag in the population files to include a DOI entry, with an added citation() method in population model that prints the DOI for citing specific models.

### PR DESCRIPTION
**Pull request by caitlinbegbie**
Fixes #46 .

## Description of the Change
I have added a citation feature for all three population models in the following way:

1. Updated the .asdf files for the three models to include a citation of the form ["10.3847/1538-4357/ab5fd3", "10.3847/1538-4357/aca09d"].
2. Updated model.py and test_model.py to account for this new feature and confirmed it was behaving as expected.
3. Updated documentation, including tutorials.rst and popsycle_model_example.ipynb, to explain this adjustment and prevent potential errors.

## Checklist

Please check all that apply to your proposed changes

- [ ] Added package dependency
- [ ] Added data
- [x] Documentation change
- [x] code change

### **Additional context**
I had issues simply adding the citation feature in the raithel18.asdf file, so I rewrote the file with the change and replaced the previous version. The other two files gave no trouble adding the change. Just thought it might be worth noting that the raithel.asdf file is new, but does not seem to be creating any problems.

### CODE REVIEW

**Review by astrophpeter — CHANGES_REQUESTED** [review]
Docs are failing see (https://readthedocs.org/projects/popclass/builds/25797043/) I think there is a stray - instead of = in one of the notebooks. Looks great and ready to merge once that is fixed :)

**Comment by caitlinbegbie** [comment]
Whoops, you are completely right! I fixed the typo in the notebook and all should (hopefully) be good to go now :)

**Comment by astrophpeter** [comment]
> Whoops, you are completely right! I fixed the typo in the notebook but the test is still failing :( Any idea why this might be the case?

Its because the notebooks import the pypi version of popclass not the cutting edge dev version. This will resolve its self when I push a new package version :) I added a setting to get the notebooks to ignore the errors for now.

**Comment by astrophpeter** [comment]
Will merge now, great work :)

**Comment by caitlinbegbie** [comment]
Thank you, happy it's all working out!!

**Pull request merged**
